#!/usr/bin/env python3

import yaml
import sys
import argparse
from xdg import xdg_config_home, xdg_data_home
from os.path import exists as file_exists


def default_config_file():
    xdg_config_file=str(xdg_config_home())+"/gradeTracker/config.yml"
    if file_exists(xdg_config_file):
        return xdg_config_file
    elif file_exists('config.yml'):
        return 'config.yml'
    else:
        print('No config file found. Please place one at $XDG_CONFIG_HOME/gradeTracker/config.yml', file=sys.stderr)
        sys.exit()

def default_data_file(config):
    xdg_data_file=str(xdg_data_home())+"/gradeTracker/data.yml"
    if "data_file" in config:
        if file_exists(config["data_file"]):
            return config["data_file"]
        else:
            print(f'{config["data_file"]} is set as the data file but does not exist.\nThis must be an explicit path (i.e. does not contain ~ or environment variables)', file=sys.stderr)
            sys.exit()

    elif file_exists(xdg_data_file):
        return xdg_data_file
    elif file_exists('data.yml'):
        return 'data.yml'
    else:
        print('No data file found. Please place one at $XDG_DATA_HOME/gradeTracker/data.yml', file=sys.stderr)
        sys.exit()


parser = argparse.ArgumentParser()

parser.add_argument('-c', '--config-file',
                    help='The file used for configuration',
                    default=default_config_file(),
                    dest='config_file')

parser.add_argument('-d', '--data-file',
                    help='The file used for data',
                    default=None,
                    dest='data_file')

parser.add_argument('--ignore-unmarked',
                    help='If enabled, gradeTracker will not assume that unmarked modules are 0.',
                    dest='ignore_unmarked',
                    default=None,
                    action='store_true')

parser.add_argument('--use-unmarked',
                    help='If enabled, gradeTracker will assume that unmarked modules are 0.',
                    dest='ignore_unmarked',
                    default=None,
                    action='store_false')

parser.add_argument('--indent-string',
                    help='String that should be used to indent each option. "  " by default',
                    dest='indent_string',
                    default=None)

parser.add_argument('--post-string',
                    help='String that should be displayed after a grade is shown. "%" by default',
                    dest='post_string',
                    default=None)

parser.add_argument('--total-weighting-tolerance',
                    help='How close do we require the total weight to be to 100',
                    dest='total_weighting_tolerance',
                    default=None)

parser.add_argument('command',
                    help='Command to run',
                    choices=['print-marks', 'print-modules', 'check-config'])


def print_module_tree(module_list, prestring):
    """Prints a tree of modules from module_list.
    prestring will be put at the start of each message,
    and 2 spaces will be appended for each added layer"""
    for module in module_list:
        fstring=f'{prestring}{module["module"]} with weighting {module["weighting"]}{args.post_string}'
        if 'percent' in module:
            fstring+=f' and percentage {module["percent"]}{args.post_string}'
        print(fstring)
        if 'modules' in module:
            # This means there are submodules, so we should recurse into them
            print_module_tree(module["modules"], prestring+args.indent_string)

def check_module_tree(module_list):
    """Checks the module tree inside module_list.
    Will check that the total percentage is 100,
    and will throw an error otherwise"""
    total_weighting = 0
    for module in module_list:
        total_weighting += module["weighting"]
        if 'modules' in module:
            if check_module_tree(module["modules"]) == False:
                print(f"Config File Invalid \n{module['module']}'s submodules do not sum to 100%", file=sys.stderr)
                sys.exit()
    if abs(total_weighting - 100) > args.total_weighting_tolerance:
        # The percentages do not add up to 100, we should throw an error
        return False


def calc_percentage(module_list, module_name, prestring):
    """Calculates the weighted average percentage inside module_list,
    respecting, ignore_unmarked
    It will also compute print_strings in case we want to print later"""

    # First we want to generate lists of all of the percentages and weightings on this level
    percentages=[]
    weightings=[]
    # This an array of strings ready for later printing
    global print_strings
    if 'print_strings' not in globals():
        print_strings=[]

    for module in module_list:
        if 'modules' in module:
            # we need to recursively compute it
            percent = calc_percentage(module['modules'], module['module'], prestring+args.indent_string)
        elif 'percent' in module:
            # We are at the bottom of the tree, this is as small as we get
            percent=module["percent"]
            print_strings.append(f"{prestring+args.indent_string}{module['module']}: {percent}{args.post_string}")
        else:
            # This module currently has no percent,
            # so we don't want to append to the list
            continue
        weighting=module["weighting"]
        percentages.append(percent)
        weightings.append(weighting)

    # If we want to ignore unmarked, we need to adjust the weightings so that this happens
    if args.ignore_unmarked:
        # We don't want to assume 0, so we need to recompute weightings
        # We do this by finding a scale factor to scale them by so the total weighting is 100
        total_weighting=sum(weightings)
        scale_factor=100/total_weighting
        # Now we update weightings to be scaled by the scale factor
        for idx,weighting in enumerate(weightings):
            weightings[idx]=scale_factor*weighting

    # Now we can compute a list of weighted percentages
    weightedPercentages=[]
    for idx,percent in enumerate(percentages):
        weightedPercentages.append(percent*weightings[idx]/100)

    # and then compute the sum
    avg=sum(weightedPercentages)
    print_strings.append(f'{prestring}{module_name}: {avg}{args.post_string}')
    return avg




def check_data_file(data):
    """Checks whether the data file is valid"""
    # This essentially wraps check_module_tree to additionally check the outer layer
    if check_module_tree(data["modules"]) == False:
        print(f"Data File Invalid \nRoot tree's percent does not sum to 100", file=sys.stderr)
        sys.exit()


def open_config_file():
    """Open and check the config file is valid.
    Returns a dictionary containing the config"""

    # I want to parse the arguments here so I can set the default values from
    # the config file before running anything else
    global args
    args=parser.parse_args()

    with open(args.config_file,"r") as config_file:
        # Load the config file
        try:
            config = yaml.safe_load(config_file)
        except yaml.YAMLError as exc:
            # The yaml in the config is invalid. tell the user and return
            print("Config File Invalid, YAML processor returns:")
            print(exc,file=sys.stderr)
            sys.exit()

        if args.data_file==None:
            args.data_file=default_data_file(config)

        if "total_weighting_tolerance" in config:
            args.total_weighting_tolerance=config["total_weighting_tolerance"]
        else:
            args.total_weighting_tolerance=5

        with open(args.data_file,"r") as data_file:
            # Load the data file
            try:
                data = yaml.safe_load(data_file)
            except yaml.YAMLError as exc:
                # The yaml in the data is invalid, tell the user and return
                print("Data File Invalid, YAML processor returns:")
                print(exc,file=sys.stderr)
                sys.exit()
            # Check the modules in the data file are configured validly
            check_data_file(data)
    if args.ignore_unmarked==None:
        if "ignore_unmarked" in config:
            args.ignore_unmarked=config["ignore_unmarked"]
        else:
            args.ignore_unmarked=True
    if args.indent_string==None:
        if "indent_string" in config:
            args.indent_string=config["indent_string"]
        else:
            args.indent_string="  "

    if args.post_string==None:
        if "post_string" in config:
            args.post_string=config["post_string"]
        else:
            args.post_string="%"

    return config, data


config, data = open_config_file()


if args.command=='print-marks':
    calc_percentage(data["modules"],'Overall','')
    # print_strings give us the right strings but upside down, so we reverse
    # them and then print them
    print_strings.reverse()
    for string in print_strings:
        print(string)

elif args.command=='print-modules':
    print_module_tree(data["modules"],"")

elif args.command=='check-config':
    # We've already checked the config is valid so we can just tell the user
    print("Config is valid")
