#!/usr/bin/env python3

import yaml
import sys
import argparse
from xdg import xdg_config_home, xdg_data_home
from os.path import exists as file_exists

def default_config_file():
    xdg_config_file=str(xdg_config_home())+"/gradeTracker/config.yml"
    if file_exists(xdg_config_file):
        return xdg_config_file
    elif file_exists('config.yml'):
        return 'config.yml'
    else:
        print('No config file found. Please place one at $XDG_CONFIG_HOME/gradeTracker/config.yml', file=sys.stderr)
        sys.exit()

def default_data_file():
    xdg_data_file=str(xdg_data_home())+"/gradeTracker/data.yml"
    if file_exists(xdg_data_file):
        return xdg_data_file
    elif file_exists('data.yml'):
        return 'data.yml'
    else:
        print('No data file found. Please place one at $XDG_DATA_HOME/gradeTracker/data.yml', file=sys.stderr)
        sys.exit()


parser = argparse.ArgumentParser()

parser.add_argument('-c', '--config-file',
                    help='The file used for configuration',
                    default=default_config_file(),
                    dest='config_file')

parser.add_argument('-d', '--data-file',
                    help='The file used for data',
                    default=default_data_file(),
                    dest='data_file')

parser.add_argument('--ignore-unmarked',
                    help='If enabled, gradeTracker will not assume that unmarked modules are 0.',
                    dest='ignore_unmarked',
                    default=None,
                    action='store_true')

parser.add_argument('--use-unmarked',
                    help='If enabled, gradeTracker will assume that unmarked modules are 0.',
                    dest='ignore_unmarked',
                    default=None,
                    action='store_false')


def print_module_tree(module_list, prestring):
    """Prints a tree of modules from module_list.
    prestring will be put at the start of each message,
    and 2 spaces will be appended for each added layer"""
    for module in module_list:
        print(f'{prestring}Module {module["module"]} with percentage {module["weighting"]}')
        if 'modules' in module:
            # This means there are submodules, so we should recurse into them
            print_module_tree(module["modules"], prestring+"  ")

def check_module_tree(module_list):
    """Checks the module tree inside module_list.
    Will check that the total percentage is 100,
    and will throw an error otherwise"""
    total_weighting = 0
    for module in module_list:
        total_weighting += module["weighting"]
        if 'modules' in module:
            if check_module_tree(module["modules"]) == False:
                print(f"Config File Invalid \n{module['module']}'s submodules do not sum to 100%", file=sys.stderr)
                sys.exit()
    if total_weighting != 100:
        # The percentages do not add up to 100, we should throw an error
        return False


def calc_percentage(module_list):
    """Calculates the weighted average percentage inside module_list,
    assuming anything without a percent is 0"""

    # First we want to generate lists of all of the percentages and weightings on this level
    percentages=[]
    weightings=[]
    for module in module_list:
        if 'modules' in module:
            # we need to recursively compute it
            percent = calc_percentage(module['modules'])
        elif 'percent' in module:
            percent=module["percent"]
        else:
            # This module currently has no percent,
            # so we don't want to append to the list
            continue
        weighting=module["weighting"]
        percentages.append(percent)
        weightings.append(weighting)

    # If we want to ignore unmarked, we need to adjust the weightings so that this happens
    if args.ignore_unmarked:
        # We don't want to assume 0, so we need to recompute weightings
        # We do this by finding a scale factor to scale them by so the total weighting is 100
        total_weighting=sum(weightings)
        scale_factor=100/total_weighting
        # Now we update weightings to be scaled by the scale factor
        for idx,weighting in enumerate(weightings):
            weightings[idx]=scale_factor*weighting

    # Now we can compute a list of weighted percentages
    weightedPercentages=[]
    for idx,percent in enumerate(percentages):
        weightedPercentages.append(percent*weightings[idx]/100)

    # and then return the average
    return sum(weightedPercentages)/len(weightedPercentages)




def check_data_file(data):
    """Checks whether the data file is valid"""
    # This essentially wraps check_module_tree to additionally check the outer layer
    if check_module_tree(data["modules"]) == False:
        print(f"Data File Invalid \nRoot tree's percent does not sum to 100", file=sys.stderr)
        sys.exit()


def open_config_file():
    """Open and check the config file is valid.
    Returns a dictionary containing the config"""

    # I want to parse the arguments here so I can set the default values from
    # the config file before running anything else
    global args
    args=parser.parse_args()

    with open(args.config_file,"r") as config_file:
        # Load the config file
        try:
            config = yaml.safe_load(config_file)
        except yaml.YAMLError as exc:
            # The yaml in the config is invalid. tell the user and return
            print("Config File Invalid, YAML processor returns:")
            print(exc,file=sys.stderr)
            sys.exit()

        with open(args.data_file,"r") as data_file:
            # Load the data file
            try:
                data = yaml.safe_load(data_file)
            except yaml.YAMLError as exc:
                # The yaml in the data is invalid, tell the user and return
                print("Data File Invalid, YAML processor returns:")
                print(exc,file=sys.stderr)
                sys.exit()
            # Check the modules in the data file are configured validly
            check_data_file(data)
    if args.ignore_unmarked==None:
        if "ignore_unmarked" in config:
            args.ignore_unmarked=config["ignore_unmarked"]
        else:
            args.ignore_unmarked=True
    return config, data


config, data = open_config_file()

print(calc_percentage(data["modules"]))
